server:
  port: ${PORT:8080}

spring:
  application:
    name: nextgen-hrms-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hrms_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:abh@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET:bmV4dGdlbi1ocm1zLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLTIwMjY=}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.hrms.apar: INFO
